name: PostgreSQL Doc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U sphinx
    - name: Pull document source files
      uses: actions/checkout@master
    - name: Build Document By Sphinx
      run: |
        ./make html
