name: PostgreSQL Doc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U sphinx
        pip install sphinx-rtd-theme
    - name: Build Document By Sphinx
      run: |
        sphinx-build -b html ./source ./build
    - name: Deploy Document
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.SSHKEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $HOST > ~/.ssh/known_hosts
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
        tar -czvf pgsql-doc.tar.gz ./build/*
        scp -v ./pgsql-doc.tar.gz $USERNAME@$HOST:/home/wwwroot/pgsql-doc
        ssh $USERNAME@$HOST
        cd /home/wwwroot/pgsql-doc
        tar -xzvf pgsql-doc.tar.gz
        
